# Main attributes for the main README
add_index_numbers: true
main_title: "Resident Evil Ruleset"

# main structure node. [!] DON'T CHANGE THIS NAME
# just add your own structure inside this node.
structure:

  # [main: setup]
  setup_inicial:
    title: "Setup Inicial"
    go_back: true
    contents:
      tanda_1:
        go_back: true
        readme: "t1"
      tanda_2:
        go_back: true
        readme: "t2"
      tanda_3:
        go_back: true
        readme: "t3"

  # [main: personajes]
  personajes_&_tiers:
    title: "Personajes & Tiers"
    go_back: true
    contents:
      tier_S:
        go_back: true
        readme: "t s"
      tier_A:
        go_back: true
        readme: "t a"
      tier_B:
        go_back: true
        readme: "t b"
      banlist:
        go_back: true
        readme: "Barry is here\n\n{img:barry_fake.jpg}"

  # [main: armas]
  armas:
    title: "Armas"
    go_back: true
    contents:
      limited:
        go_back: true
        readme: "armas limitadas"

  # [main: mansion]
  mansion:
    title: "Reglas de Mansion"
    go_back: true
    contents:
      specific_rules:
        title: "Reglas Especificas de Monstruos"
        go_back: true
        contents:
          grillo:
            go_back: true
            readme: | 
              > Cuando el grillo es revelado, te quita una carta attachada cualquiera,
              si son 2 o mas cartas attachadas, se quita una al azar.
              (ejemplo: plantas amarillas, mapa, etc)\n\n{img:grillo.jpg}

