# Main attributes for the main README
add_index_numbers: true
main_title: "Resident Evil Ruleset"

# main structure node. [!] DON'T CHANGE THIS NAME
# just add your own structure inside this node.
structure:

  # [main: setup]
  setup_inicial:
    title: "Setup Inicial"
    go_back: true
    contents:
      # [sub]
      tanda_1:
        title: "Tanda 1 (Inicial)"
        go_back: true
        readme: |
          \n> #### ITEMS\n
          {img:setup_tanda_1_items.jpg}
          \n> #### ACCIONES\n
          {img:setup_tanda_1_actions.jpg}
      # [sub]
      tanda_2:
        title: "Tanda 2 - (8 cds)"
        go_back: true
        readme: |
          > **TANDA 2** - 1er jugador en 8 CONDECORACIONES\n
          {img:setup_tanda_2_all.jpg}
          \n---\n
          > **ITEMS**\n
          {img:setup_tanda_2_items.jpg}
          \n---\n
          > **LIMITADAS**\n
          {img:setup_tanda_2_limited.jpg}
      # [sub]
      tanda_3:
        title: "Tanda 3 - (15 cds)"
        go_back: true
        readme: |
          > **TANDA 3** - 1er jugador en 15 CONDECORACIONES\n
          {img:setup_tanda_3_all.jpg}
          \n---\n
          > #### VISTA ITEMS\n
          {img:setup_tanda_3_items.jpg}
          \n---\n
          > #### VISTA LIMITADAS\n
          {img:setup_tanda_3_limited.jpg}
      # [sub]
      tanda_de_premios_mansion:
        title: "Tanda de Premios Mansion"
        go_back: true
        readme: |
          > **TANDA DE PREMIOS MANSION.**
          Solo disponible si eliminas 1 monstruo de la mansion de alto nivel.\n
          {img:mansion_rewards.jpg}
      # [sub]
      mano_inicial:
        title: "Mano Inicial"
        go_back: true
        readme: ""

  # [main: personajes]
  personajes_&_tiers:
    title: "Personajes & Tiers"
    go_back: true
    contents:
      # [sub]
      tier_S:
        go_back: true
        readme: "{img:char_tier_s_list.jpg}"
      # [sub]
      tier_A:
        go_back: true
        readme: "{img:char_tier_a_list.jpg}"
      # [sub]
      tier_B:
        go_back: true
        readme: |
          {img:char_tier_b_list.jpg}
          \n---\n
          > Vista particionada\n
          {img:char_tier_b_part1.jpg}\n
          {img:char_tier_b_part2.jpg}\n
          {img:char_tier_b_part3.jpg}
      # [sub]
      banlist:
        go_back: true
        readme: | 
          > Barry esta baneado porque facilmente puede hacer +100 por turno.
          Y ocasionalmente puede hacer doble o triple exploracion. Rompe Juegos.
          \n\n{img:char_barry_banned.jpg}

  # [main: armas]
  armas:
    title: "Armas"
    go_back: true
    contents:
      # [sub]
      limited:
        go_back: true
        readme: "armas limitadas"

  # [main: actions]
  acciones:
    title: "Acciones"
    go_back: true
    contents:
      # [sub]
      limited:
        go_back: true
        readme: "acciones limitadas"

  # [main: mansion]
  mansion:
    title: "Reglas de Mansion"
    go_back: true
    contents:
      # [sub]
      specific_rules:
        title: "Reglas Especificas de Monstruos"
        go_back: true
        contents:
          # [sub]
          grillo:
            go_back: true
            readme: | 
              > Cuando el grillo es eliminado, te quita una carta attachada cualquiera,
              si son 2 o mas cartas attachadas, se quita una al azar.
              (ejemplo: plantas amarillas, mapa, etc)\n\n{img:monster_grillo.jpg}

  # [main: reglas en general]
  general_rules:
    title: "Reglas En General"
    go_back: true
    contents:
      # [sub]
      infection:
        go_back: true
        readme: |
          > El nivel de infeccion total es [3]. Si llegas a ese limite, pierdes la vida actual.
          Se procedera a continuar con el siguiente CONTINUE (si todavia hay)
          vida llena, infeccion en 0 y fichas maricas correspondientes.

  # [main: discusiones]
  discussions:
    title: "Discusiones"
    go_back: true
    contents:
      # [sub]
      infection_level:
        title: "Nivel de Infeccion 3 o 4"
        go_back: true
        readme: ""
